/** Hardcoded Med Supp (Medicare Supplement) carriers and plan options. */

export const MED_SUPP_CARRIERS = [
  "Accendo",
  "ACE Property Casualty",
  "Aetna",
  "Aflac",
  "Allstate",
  "AMA",
  "American Amicable",
  "American Benefit Life",
  "American Continental",
  "American Fidelity",
  "American Financial Security Life",
  "American Home Life",
  "American National",
  "American Republic",
  "American Retirement Life",
  "Americo",
  "Amerigroup",
  "Ameritas",
  "Anthem",
  "AR Blue Cross",
  "Assured Life",
  "Asuris",
  "Atlantic Capital Life",
  "Atlantic Coast Life",
  "AultCare's Prime",
  "Avera Health Plans",
  "Bankers Fidelity",
  "Bankers Life",
  "BCBS of Arizona",
  "BCBS of IL, NM",
  "BCBS of Kansas",
  "BCBS of Kansas City",
  "BCBS of LA",
  "BCBS of Massachusetts",
  "BCBS of Michigan",
  "BCBS of Minnesota",
  "BCBS of MT",
  "BCBS of ND",
  "BCBS of Nebraska",
  "BCBS of North Carolina",
  "BCBS Of Oklahoma",
  "BCBS of Rhode Island",
  "BCBS of South Carolina",
  "BCBS of Tennessee",
  "BCBS of TX",
  "Blue Cross",
  "Blue Cross of ID",
  "Blue Shield of CA",
  "Capital BlueCross",
  "Capitol Life",
  "CareFirst BC",
  "Catholic Financial Life",
  "Central States Indemnity",
  "Central States of Omaha",
  "Cigna",
  "Colonial Penn",
  "Combined Insurance",
  "Combined Insurance Co",
  "Companion Life",
  "ConnectiCare",
  "Conseco",
  "Continental Life",
  "Coventry",
  "CSI Life",
  "Educators Mutual Insurance",
  "Elips Life",
  "Empire BCBS",
  "EPIC Life",
  "Equitable Life",
  "Erie Insurance",
  "Everence",
  "Everest",
  "Excellus",
  "Fallon",
  "Federal Life",
  "First Community",
  "First Health",
  "Florida Blue",
  "Forethought",
  "Garden State Life",
  "Gerber",
  "Globe Life",
  "Government Personnel",
  "GPM",
  "GPM Life",
  "Great Southern Life",
  "Guaranteed Trust Life",
  "HAP",
  "Harvard Pilgrim",
  "Health Alliance",
  "Health New England",
  "HealthNet",
  "HealthPartners",
  "HealthSpring",
  "Heartland National Life",
  "Highmark Health",
  "Horizon",
  "Humana",
  "INA",
  "Individual Assurance",
  "KSKJ Life",
  "LCBA",
  "Liberty Bankers",
  "Liberty National",
  "LifeShield",
  "Loyal American",
  "Lumico",
  "Manhattan Life",
  "Medica",
  "Medico",
  "MedMutual",
  "Moda Health",
  "Montana Health Co-Op",
  "Mountain Health",
  "Mutual of Omaha",
  "Nassau Life",
  "National General",
  "New Era Life",
  "Old Surety",
  "Omaha Insurance Company",
  "Omaha Supplemental Insurance Co",
  "Order of United",
  "Oxford Life",
  "Pan American",
  "Paramount Insurance",
  "Pekin Life",
  "Philadelphia American",
  "Physicians Mutual",
  "Premera",
  "PriorityHealth",
  "Prosperity Life",
  "Providence",
  "Puritan Life",
  "QualChoice",
  "Quartz",
  "Regence",
  "Renaissance",
  "Reserve National",
  "Royal Arcanum",
  "SBLI",
  "Sentinel Security",
  "SGIC",
  "Shenandoah Life",
  "Sierra Health and Life",
  "Southern Guarantee Life",
  "Standard Life",
  "State Farm",
  "State Farm Mutual",
  "State Mutual",
  "Sterling",
  "Stonebridge",
  "Summa Insurance",
  "THP Insurance Company",
  "Thrivent",
  "Thrivent Financial",
  "Transamerica Life",
  "UCare",
  "UHICA",
  "UICA",
  "Unified Life",
  "Union Security",
  "United American",
  "United Commercial",
  "United of Omaha",
  "United World Life",
  "UnitedHealthcare",
  "US Fire",
  "USAA",
  "USIC",
  "Washington National",
  "Wellabe",
  "Wellmark BCBS",
  "Wellpoint",
  "Western Catholic Union",
  "Woodmen Life",
  "WPS Health Insurance",
] as const

export const MED_SUPP_PLANS = [
  "1",
  "1A",
  "Core",
  "High Ded. Plan F",
  "High Ded. Plan G",
  "Innovative Plan G",
  "Legacy C",
  "Plan A",
  "Plan B",
  "Plan C",
  "Plan D",
  "Plan F",
  "Plan F Extra",
  "Plan G",
  "Plan G Extra",
  "Plan I",
  "Plan J",
  "Plan K",
  "Plan L",
  "Plan M",
  "Plan N",
  "Plan N Extra",
  "1 (GI)",
  "1A (GI)",
  "Basic (GI)",
  "Basic Extended (GI)",
  "Basic Select (GI)",
  "Core (GI)",
  "High Ded. Plan F (GI)",
  "High Ded. Plan G (GI)",
  "Plan A (GI)",
  "Plan B (GI)",
  "Plan C (GI)",
  "Plan D (GI)",
  "Plan F (GI)",
  "Plan F Extra (GI)",
  "Plan G (GI)",
  "Plan G Extra (GI)",
  "Plan K (GI)",
  "Plan L (GI)",
  "Plan M (GI)",
  "Plan N (GI)",
  "SELECT Plan A",
  "SELECT Plan B",
  "SELECT Plan C",
  "SELECT Plan D",
  "SELECT Plan F",
  "SELECT Plan G",
  "SELECT Plan J",
  "SELECT Plan K",
  "SELECT Plan L",
  "SELECT Plan L536",
  "SELECT Plan L537",
  "SELECT Plan L537 w/ F011 Rider",
  "SELECT Plan L538",
  "SELECT Plan L538 w/ F012 Rider",
  "SELECT Plan L539",
  "SELECT Plan M",
  "SELECT Plan N",
  "SELECT Plan S041",
  "SELECT Plan S042",
  "SELECT Plan S042 w/ F021 Rider",
  "Basic",
  "Basic Extended",
  "Basic Select",
] as const

/** Med Supp plans grouped with separators for dropdown display. */
export const MED_SUPP_PLANS_GROUPED: { label?: string; plans: readonly string[] }[] = [
  {
    plans: [
      "1",
      "1A",
      "Core",
      "High Ded. Plan F",
      "High Ded. Plan G",
      "Innovative Plan G",
      "Legacy C",
      "Plan A",
      "Plan B",
      "Plan C",
      "Plan D",
      "Plan F",
      "Plan F Extra",
      "Plan G",
      "Plan G Extra",
      "Plan I",
      "Plan J",
      "Plan K",
      "Plan L",
      "Plan M",
      "Plan N",
      "Plan N Extra",
    ],
  },
  {
    label: "Guaranteed Issue",
    plans: [
      "1 (GI)",
      "1A (GI)",
      "Basic (GI)",
      "Basic Extended (GI)",
      "Basic Select (GI)",
      "Core (GI)",
      "High Ded. Plan F (GI)",
      "High Ded. Plan G (GI)",
      "Plan A (GI)",
      "Plan B (GI)",
      "Plan C (GI)",
      "Plan D (GI)",
      "Plan F (GI)",
      "Plan F Extra (GI)",
      "Plan G (GI)",
      "Plan G Extra (GI)",
      "Plan K (GI)",
      "Plan L (GI)",
      "Plan M (GI)",
      "Plan N (GI)",
    ],
  },
  {
    label: "Medicare SELECT",
    plans: [
      "SELECT Plan A",
      "SELECT Plan B",
      "SELECT Plan C",
      "SELECT Plan D",
      "SELECT Plan F",
      "SELECT Plan G",
      "SELECT Plan J",
      "SELECT Plan K",
      "SELECT Plan L",
      "SELECT Plan L536",
      "SELECT Plan L537",
      "SELECT Plan L537 w/ F011 Rider",
      "SELECT Plan L538",
      "SELECT Plan L538 w/ F012 Rider",
      "SELECT Plan L539",
      "SELECT Plan M",
      "SELECT Plan N",
      "SELECT Plan S041",
      "SELECT Plan S042",
      "SELECT Plan S042 w/ F021 Rider",
    ],
  },
  {
    label: "Other",
    plans: ["Basic", "Basic Extended", "Basic Select"],
  },
]

export type MedSuppCarrier = (typeof MED_SUPP_CARRIERS)[number]
export type MedSuppPlan = (typeof MED_SUPP_PLANS)[number]
