import type { Lead, Client, Activity, Task, Flow, Stage, NoteEntry } from "./types"

function notes(...entries: [string, string][]): NoteEntry[] {
  return entries.map(([text, createdAt]) => ({ text, createdAt }))
}

// Use a fixed base date to prevent SSR/client hydration mismatches
const BASE = "2026-02-17T12:00:00.000Z"
const day = (offset: number) => {
  const d = new Date(BASE)
  d.setDate(d.getDate() + offset)
  return d.toISOString()
}

export const agents = ["Sarah Mitchell", "James Carter", "Lisa Wang"]

// Default flow and stages (same 7 as legacy LeadStage)
export const defaultFlow: Flow = {
  id: "flow-leads",
  name: "Leads",
  order: 0,
  isDefault: true,
  createdAt: BASE,
}

const STAGE_IDS = {
  New: "stage-new",
  Contacted: "stage-contacted",
  Scheduled: "stage-scheduled",
  "No-Show": "stage-no-show",
  Nurture: "stage-nurture",
  Converted: "stage-converted",
  "Closed-Lost": "stage-closed-lost",
} as const

export const defaultStages: Stage[] = [
  { id: STAGE_IDS.New, flowId: defaultFlow.id, name: "New", order: 0, colorKey: "#EF4444" },
  { id: STAGE_IDS.Contacted, flowId: defaultFlow.id, name: "Contacted", order: 1, colorKey: "#3B82F6" },
  { id: STAGE_IDS.Scheduled, flowId: defaultFlow.id, name: "Scheduled", order: 2, colorKey: "#A855F7" },
  { id: STAGE_IDS["No-Show"], flowId: defaultFlow.id, name: "No-Show", order: 3, colorKey: "#06B6D4" },
  { id: STAGE_IDS.Nurture, flowId: defaultFlow.id, name: "Nurture", order: 4, colorKey: "#EAB308" },
  { id: STAGE_IDS.Converted, flowId: defaultFlow.id, name: "Converted", order: 5, colorKey: "#22C55E" },
  { id: STAGE_IDS["Closed-Lost"], flowId: defaultFlow.id, name: "Closed-Lost", order: 6, colorKey: "#374151" },
]

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    firstName: "Robert",
    lastName: "Johnson",
    phone: "(555) 123-4567",
    email: "robert.j@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: notes(
      ["Interested in Medicare Advantage plans", day(-1)],
      ["Prefers morning calls", day(-1)]
    ),
    tags: ["T65", "Priority"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-2),
    updatedAt: day(-1),
    nextFollowUpAt: day(1),
    dob: "1961-05-15",
  },
  {
    id: "lead-2",
    firstName: "Patricia",
    lastName: "Williams",
    phone: "(555) 234-5678",
    email: "pat.w@email.com",
    source: "Referral",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: notes(
      ["Referred by existing client Mary Adams", day(-1)],
      ["Has questions about Part D", day(-1)]
    ),
    tags: ["Referral", "Part D"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-5),
    updatedAt: day(-1),
    nextFollowUpAt: day(2),
    dob: "1961-08-22",
  },
  {
    id: "lead-3",
    firstName: "Michael",
    lastName: "Brown",
    phone: "(555) 345-6789",
    email: "m.brown@email.com",
    source: "Website",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Scheduled,
    notes: notes(
      ["Appointment set for Thursday", day(-2)],
      ["Wants to compare Supplement plans", day(-2)]
    ),
    tags: ["Supplement", "Appointment"],
    assignedTo: "James Carter",
    createdAt: day(-7),
    updatedAt: day(-2),
    nextFollowUpAt: day(3),
    dob: "1961-03-10",
  },
  {
    id: "lead-4",
    firstName: "Jennifer",
    lastName: "Davis",
    phone: "(555) 456-7890",
    email: "j.davis@email.com",
    source: "Call-in",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: notes(["Called asking about enrollment periods", day(-1)]),
    tags: ["T65"],
    assignedTo: "Lisa Wang",
    createdAt: day(-1),
    updatedAt: day(-1),
    nextFollowUpAt: day(0),
    dob: "1961-11-03",
  },
  {
    id: "lead-5",
    firstName: "William",
    lastName: "Miller",
    phone: "(555) 567-8901",
    email: "w.miller@email.com",
    source: "Direct Mail",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Nurture,
    notes: notes(
      ["Not ready yet", day(-5)],
      ["Follow up in 2 weeks", day(-5)],
      ["Interested in MAPD", day(-5)]
    ),
    tags: ["Long-term", "MAPD"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-30),
    updatedAt: day(-5),
    nextFollowUpAt: day(9),
  },
  {
    id: "lead-6",
    firstName: "Elizabeth",
    lastName: "Wilson",
    phone: "(555) 678-9012",
    email: "e.wilson@email.com",
    source: "Event",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: notes(
      ["Met at senior center event", day(-1)],
      ["Spouse also needs coverage", day(-1)]
    ),
    tags: ["Couple", "Event"],
    assignedTo: "James Carter",
    createdAt: day(-3),
    updatedAt: day(-1),
    nextFollowUpAt: day(1),
    dob: "1961-07-19",
  },
  {
    id: "lead-7",
    firstName: "Thomas",
    lastName: "Anderson",
    phone: "(555) 789-0123",
    email: "t.anderson@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Converted,
    notes: notes(
      ["Enrolled in Aetna MAPD plan", day(-3)],
      ["Very satisfied", day(-3)]
    ),
    tags: ["MAPD", "Converted"],
    assignedTo: "Lisa Wang",
    createdAt: day(-45),
    updatedAt: day(-3),
    nextFollowUpAt: null,
    dob: "1960-12-08",
    clientId: "client-1",
  },
  {
    id: "lead-8",
    firstName: "Margaret",
    lastName: "Taylor",
    phone: "(555) 890-1234",
    email: "m.taylor@email.com",
    source: "Referral",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS["Closed-Lost"],
    notes: notes(
      ["Went with another agent", day(-10)],
      ["May reconsider at AEP", day(-10)]
    ),
    tags: ["Lost"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-60),
    updatedAt: day(-10),
    nextFollowUpAt: null,
  },
  {
    id: "lead-9",
    firstName: "Charles",
    lastName: "Moore",
    phone: "(555) 901-2345",
    email: "c.moore@email.com",
    source: "Website",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: notes(["Submitted form online", day(0)]),
    tags: ["Online", "T65"],
    assignedTo: "James Carter",
    createdAt: day(0),
    updatedAt: day(0),
    nextFollowUpAt: day(1),
    dob: "1961-09-25",
  },
  {
    id: "lead-10",
    firstName: "Sandra",
    lastName: "Jackson",
    phone: "(555) 012-3456",
    email: "s.jackson@email.com",
    source: "Call-in",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Scheduled,
    notes: notes(
      ["Appointment next Monday", day(-1)],
      ["Needs help with Part B enrollment", day(-1)]
    ),
    tags: ["Part B", "Appointment"],
    assignedTo: "Lisa Wang",
    createdAt: day(-4),
    updatedAt: day(-1),
    nextFollowUpAt: day(4),
  },
  {
    id: "lead-11",
    firstName: "Daniel",
    lastName: "White",
    phone: "(555) 111-2222",
    email: "d.white@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: notes(["Interested in supplement plans", day(-2)]),
    tags: ["Supplement"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-6),
    updatedAt: day(-2),
    nextFollowUpAt: day(2),
  },
  {
    id: "lead-12",
    firstName: "Nancy",
    lastName: "Harris",
    phone: "(555) 333-4444",
    email: "n.harris@email.com",
    source: "Event",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Nurture,
    notes: notes(
      ["Needs to wait until retirement", day(-8)],
      ["Follow up in Q4", day(-8)]
    ),
    tags: ["Future"],
    assignedTo: "James Carter",
    createdAt: day(-20),
    updatedAt: day(-8),
    nextFollowUpAt: day(60),
  },
]

export const mockClients: Client[] = [
  {
    id: "client-1",
    firstName: "Mary",
    lastName: "Adams",
    title: "Mrs.",
    middleName: "Jane",
    gender: "F",
    nickname: "Mary J",
    funFacts: "Loves gardening. Prefers morning calls.",
    phones: [{ id: "phone-client-1-1", number: "(555) 100-2001", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-1-1", value: "mary.adams@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-1-1", type: "Home", address: "123 Oak Street", city: "Springfield", state: "IL", zip: "62701", isPreferred: true },
      { id: "addr-client-1-2", type: "Mailing", address: "PO Box 100", city: "Springfield", state: "IL", zip: "62702", isPreferred: false },
    ],
    dob: "1961-04-12",
    turning65Date: "2026-04-12",
    preferredContactMethod: "phone",
    language: "English",
    spouseId: "client-2",
    medicareNumber: "1EG4-TE5-MK72",
    partAEffectiveDate: "2026-04-01",
    partBEffectiveDate: "2026-04-01",
    doctors: [
      {
        name: "Dr. Sarah Chen",
        specialty: "PCP",
        phone: "(555) 200-3001",
        firstName: "Sarah",
        lastName: "Chen",
        providerId: "1234567890",
        facilityAddress: "100 Medical Center Dr, Springfield, IL 62702",
        importance: "essential",
      },
      {
        name: "Dr. James Park",
        specialty: "Cardiology",
        phone: "(555) 200-3002",
        firstName: "James",
        lastName: "Park",
        providerId: "1234567891",
        facilityAddress: "200 Heart Center Way, Springfield, IL 62703",
        importance: "preferred",
      },
    ],
    medications: [
      {
        name: "Lisinopril",
        dosage: "10 MG Oral Tablet",
        frequency: "Daily",
        quantity: 30,
        rxcui: "314076",
        drugName: "Lisinopril",
        dosageDisplay: "10 MG Oral Tablet",
        doseForm: "oral tablet",
      },
      {
        name: "Atorvastatin",
        dosage: "20 MG Oral Tablet",
        frequency: "Daily",
        quantity: 30,
        rxcui: "83367",
        drugName: "Atorvastatin",
        dosageDisplay: "20 MG Oral Tablet",
        doseForm: "oral tablet",
      },
      {
        name: "Metformin",
        dosage: "500 MG Oral Tablet",
        frequency: "Twice daily",
        quantity: 60,
        rxcui: "861004",
        drugName: "Metformin",
        dosageDisplay: "500 MG Oral Tablet",
        doseForm: "oral tablet",
      },
    ],
    pharmacies: [
      { name: "CVS Pharmacy", phone: "(555) 300-4001", address: "456 Main St, Springfield, IL 62701" },
    ],
    allergies: ["Penicillin"],
    conditions: ["Hypertension", "Type 2 Diabetes", "High Cholesterol"],
    healthTracker: ["Diabetes mellitus"],
    coverages: [
      {
        id: "cov-mock-1",
        planType: "MAPD",
        carrier: "Aetna",
        planName: "Aetna Medicare Advantage Premier",
        status: "Active",
        applicationDate: "2026-03-15",
        effectiveDate: "2026-04-01",
        writtenAs: "New to Medicare",
        electionPeriod: "IEP",
        memberPolicyNumber: "",
        applicationId: "AET-2026-001234",
        hraCollected: true,
        notes: "",
      },
    ],
    createdAt: day(-90),
    updatedAt: day(-2),
  },
  {
    id: "client-2",
    firstName: "John",
    lastName: "Thompson",
    title: "Mr.",
    suffix: "Jr.",
    gender: "M",
    phones: [{ id: "phone-client-2-1", number: "(555) 100-2002", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-2-1", value: "j.thompson@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-2-1", type: "Home", address: "789 Elm Avenue", city: "Chicago", state: "IL", zip: "60601", isPreferred: true },
    ],
    dob: "1961-06-28",
    turning65Date: "2026-06-28",
    preferredContactMethod: "email",
    language: "English",
    spouseId: "client-1",
    medicareNumber: "2FH5-UF6-NL83",
    partAEffectiveDate: "2026-07-01",
    partBEffectiveDate: "2026-07-01",
    doctors: [
      {
        name: "Dr. Michael Rivera",
        specialty: "PCP",
        phone: "(555) 200-3003",
        firstName: "Michael",
        lastName: "Rivera",
        providerId: "1234567892",
        facilityAddress: "300 Clinic Blvd, Chicago, IL 60602",
      },
    ],
    medications: [
      {
        name: "Omeprazole",
        dosage: "20 MG Delayed Release Oral Capsule",
        frequency: "Daily",
        quantity: 30,
        rxcui: "316136",
        drugName: "Omeprazole",
        dosageDisplay: "20 MG Delayed Release Oral Capsule",
        doseForm: "oral capsule",
      },
    ],
    pharmacies: [
      { name: "Walgreens", phone: "(555) 300-4002", address: "321 State St, Chicago, IL 60601" },
    ],
    allergies: [],
    conditions: ["GERD"],
    coverages: [
      {
        id: "cov-mock-2",
        planType: "PDP",
        carrier: "Wellcare",
        planName: "Wellcare Medicare Rx Value Plus",
        status: "Pending/Submitted",
        applicationDate: "2026-06-01",
        effectiveDate: "2026-07-01",
        writtenAs: "Like Plan Change",
        electionPeriod: "AEP",
        memberPolicyNumber: "",
        applicationId: "WLC-2026-003456",
        hraCollected: false,
        notes: "",
      },
    ],
    createdAt: day(-60),
    updatedAt: day(-5),
  },
  {
    id: "client-3",
    firstName: "Linda",
    lastName: "Garcia",
    phones: [{ id: "phone-client-3-1", number: "(555) 100-2003", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-3-1", value: "l.garcia@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-3-1", type: "Home", address: "456 Pine Road", city: "Naperville", state: "IL", zip: "60540", isPreferred: true },
    ],
    dob: "1961-03-05",
    turning65Date: "2026-03-05",
    preferredContactMethod: "text",
    language: "Spanish",
    medicareNumber: "3GI6-VG7-OM94",
    partAEffectiveDate: "2026-03-01",
    partBEffectiveDate: "2026-03-01",
    doctors: [
      {
        name: "Dr. Ana Lopez",
        specialty: "PCP",
        phone: "(555) 200-3004",
        firstName: "Ana",
        lastName: "Lopez",
        providerId: "1234567893",
        facilityAddress: "400 Health Pkwy, Naperville, IL 60540",
        importance: "preferred",
      },
      {
        name: "Dr. Robert Kim",
        specialty: "Orthopedic Surgery",
        phone: "(555) 200-3005",
        firstName: "Robert",
        lastName: "Kim",
        providerId: "1234567894",
        facilityAddress: "500 Ortho Dr, Naperville, IL 60541",
        importance: "flexible",
      },
    ],
    medications: [
      {
        name: "Ibuprofen",
        dosage: "400 MG Oral Tablet",
        frequency: "As needed",
        quantity: 30,
        rxcui: "5640",
        drugName: "Ibuprofen",
        dosageDisplay: "400 MG Oral Tablet",
        doseForm: "oral tablet",
      },
      {
        name: "Calcium + D",
        dosage: "600 MG Oral Tablet",
        frequency: "Daily",
        quantity: 30,
        drugName: "Calcium + D",
        dosageDisplay: "600 MG Oral Tablet",
        doseForm: "oral tablet",
      },
    ],
    pharmacies: [
      { name: "Osco Pharmacy", phone: "(555) 300-4003", address: "789 Washington St, Naperville, IL 60540" },
    ],
    allergies: ["Sulfa drugs", "Latex"],
    conditions: ["Osteoarthritis"],
    coverages: [
      {
        id: "cov-mock-3",
        planType: "PDP",
        carrier: "United Healthcare",
        planName: "AARP Medigap Plan G",
        status: "Active",
        applicationDate: "2026-02-01",
        effectiveDate: "2026-03-01",
        writtenAs: "New to Medicare",
        electionPeriod: "IEP",
        memberPolicyNumber: "",
        applicationId: "UHC-2026-005678",
        hraCollected: false,
        notes: "",
      },
    ],
    createdAt: day(-120),
    updatedAt: day(-1),
  },
  {
    id: "client-4",
    firstName: "James",
    lastName: "Martinez",
    phones: [{ id: "phone-client-4-1", number: "(555) 100-2004", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-4-1", value: "j.martinez@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-4-1", type: "Home", address: "101 Maple Drive", city: "Peoria", state: "IL", zip: "61602", isPreferred: true },
    ],
    dob: "1961-08-17",
    turning65Date: "2026-08-17",
    preferredContactMethod: "phone",
    language: "English",
    medicareNumber: "4HJ7-WH8-PN05",
    partAEffectiveDate: "2026-09-01",
    partBEffectiveDate: "2026-09-01",
    doctors: [
      {
        name: "Dr. Emily Watson",
        specialty: "PCP",
        phone: "(555) 200-3006",
        firstName: "Emily",
        lastName: "Watson",
        providerId: "1234567895",
        facilityAddress: "600 Primary Care Ln, Peoria, IL 61602",
        importance: "essential",
      },
      {
        name: "Dr. David Lee",
        specialty: "Pulmonology",
        phone: "(555) 200-3007",
        firstName: "David",
        lastName: "Lee",
        providerId: "1234567896",
        facilityAddress: "700 Pulmonary Assoc, Peoria, IL 61603",
        importance: "flexible",
      },
    ],
    medications: [
      {
        name: "Albuterol",
        dosage: "90 MCG/ACTUATION Metered Dose Inhaler",
        frequency: "As needed",
        quantity: 1,
        rxcui: "1298840",
        drugName: "Albuterol",
        dosageDisplay: "90 MCG/ACTUATION Metered Dose Inhaler",
        doseForm: "metered dose inhaler",
        isPackageDrug: true,
        packageDescription: "1 CANISTER in 1 CARTON",
        packageNdc: "0173-0695-10",
      },
      {
        name: "Fluticasone",
        dosage: "50 MCG/ACTUATION Metered Dose Inhaler",
        frequency: "Twice daily",
        quantity: 1,
        rxcui: "301542",
        drugName: "Fluticasone",
        dosageDisplay: "50 MCG/ACTUATION Metered Dose Inhaler",
        doseForm: "metered dose inhaler",
        isPackageDrug: true,
        packageDescription: "1 INHALER in 1 CARTON",
        packageNdc: "00173-0672-02",
      },
    ],
    pharmacies: [
      { name: "Rite Aid", phone: "(555) 300-4004", address: "555 Adams St, Peoria, IL 61602" },
    ],
    allergies: ["Aspirin"],
    conditions: ["Asthma", "Seasonal Allergies"],
    healthTracker: ["Asthma"],
    coverages: [],
    createdAt: day(-45),
    updatedAt: day(-3),
  },
  {
    id: "client-5",
    firstName: "Barbara",
    lastName: "Robinson",
    phones: [{ id: "phone-client-5-1", number: "(555) 100-2005", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-5-1", value: "b.robinson@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-5-1", type: "Home", address: "222 Cedar Lane", city: "Evanston", state: "IL", zip: "60201", isPreferred: true },
    ],
    dob: "1961-02-20",
    turning65Date: "2026-02-20",
    preferredContactMethod: "email",
    language: "English",
    medicareNumber: "5IK8-XI9-QO16",
    partAEffectiveDate: "2026-03-01",
    partBEffectiveDate: "2026-03-01",
    doctors: [
      {
        name: "Dr. Mark Stevens",
        specialty: "PCP",
        phone: "(555) 200-3008",
        firstName: "Mark",
        lastName: "Stevens",
        providerId: "1234567897",
        facilityAddress: "800 Family Medicine Dr, Evanston, IL 60201",
      },
      {
        name: "Dr. Karen White",
        specialty: "Endocrinology",
        phone: "(555) 200-3009",
        firstName: "Karen",
        lastName: "White",
        providerId: "1234567898",
        facilityAddress: "900 Endocrine Center, Evanston, IL 60202",
      },
    ],
    medications: [
      {
        name: "Levothyroxine",
        dosage: "50 MCG Oral Tablet",
        frequency: "Daily",
        quantity: 30,
        rxcui: "105821",
        drugName: "Levothyroxine",
        dosageDisplay: "50 MCG Oral Tablet",
        doseForm: "oral tablet",
      },
      {
        name: "Vitamin B12",
        dosage: "1000 MCG Oral Tablet",
        frequency: "Daily",
        quantity: 30,
        drugName: "Vitamin B12",
        dosageDisplay: "1000 MCG Oral Tablet",
        doseForm: "oral tablet",
      },
    ],
    pharmacies: [
      { name: "CVS Pharmacy", phone: "(555) 300-4005", address: "888 Central St, Evanston, IL 60201" },
    ],
    allergies: [],
    conditions: ["Hypothyroidism"],
    coverages: [
      {
        id: "cov-mock-4",
        planType: "MAPD",
        carrier: "Humana",
        planName: "Humana Gold Plus",
        status: "Active",
        applicationDate: "2026-02-15",
        effectiveDate: "2026-03-01",
        writtenAs: "Like Plan Change (same company)",
        electionPeriod: "AEP",
        memberPolicyNumber: "",
        applicationId: "HUM-2026-009012",
        hraCollected: true,
        notes: "",
      },
    ],
    createdAt: day(-150),
    updatedAt: day(0),
  },
  {
    id: "client-6",
    firstName: "Richard",
    lastName: "Lee",
    phones: [{ id: "phone-client-6-1", number: "(555) 100-2006", type: "Cell", isPreferred: true }],
    emails: [{ id: "email-client-6-1", value: "r.lee@email.com", isPreferred: true }],
    addresses: [
      { id: "addr-client-6-1", type: "Home", address: "333 Birch Court", city: "Rockford", state: "IL", zip: "61101", isPreferred: true },
    ],
    dob: "1961-10-09",
    turning65Date: "2026-10-09",
    preferredContactMethod: "phone",
    language: "English",
    medicareNumber: "6JL9-YJ0-RP27",
    partAEffectiveDate: "2026-10-01",
    partBEffectiveDate: "2026-10-01",
    doctors: [
      {
        name: "Dr. Susan Brown",
        specialty: "PCP",
        phone: "(555) 200-3010",
        firstName: "Susan",
        lastName: "Brown",
        providerId: "1234567899",
        facilityAddress: "1000 Wellness Way, Rockford, IL 61101",
      },
    ],
    medications: [],
    pharmacies: [
      { name: "Walgreens", phone: "(555) 300-4006", address: "444 State St, Rockford, IL 61101" },
    ],
    allergies: [],
    conditions: [],
    coverages: [],
    createdAt: day(-30),
    updatedAt: day(-4),
  },
]

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    relatedType: "Client",
    relatedId: "client-1",
    type: "call",
    description: "Initial enrollment call - discussed MAPD options",
    outcome: "Scheduled follow-up",
    createdAt: day(-30),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-2",
    relatedType: "Client",
    relatedId: "client-1",
    type: "appointment",
    description: "In-person enrollment meeting",
    outcome: "Enrolled in Aetna MAPD Premier",
    dueDate: day(-15),
    completedAt: day(-15),
    createdAt: day(-15),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-3",
    relatedType: "Client",
    relatedId: "client-1",
    type: "email",
    description: "Sent welcome packet and plan summary",
    createdAt: day(-14),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-4",
    relatedType: "Lead",
    relatedId: "lead-1",
    type: "call",
    description: "Initial contact - left voicemail",
    outcome: "No answer",
    dueDate: day(-1),
    completedAt: day(-1),
    createdAt: day(-1),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-5",
    relatedType: "Lead",
    relatedId: "lead-2",
    type: "text",
    description: "Sent intro text with appointment link",
    outcome: "Replied - interested",
    createdAt: day(-2),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-6",
    relatedType: "Client",
    relatedId: "client-3",
    type: "call",
    description: "Annual review call - reviewed current coverage",
    outcome: "Satisfied with current plan",
    createdAt: day(-1),
    createdBy: "James Carter",
  },
  {
    id: "act-7",
    relatedType: "Lead",
    relatedId: "lead-3",
    type: "email",
    description: "Sent comparison of Supplement plans",
    createdAt: day(-3),
    createdBy: "James Carter",
  },
  {
    id: "act-8",
    relatedType: "Client",
    relatedId: "client-5",
    type: "note",
    description: "Client mentioned potential move to Florida - may need plan change",
    createdAt: day(0),
    createdBy: "Lisa Wang",
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    relatedType: "Client",
    relatedId: "client-1",
    relatedName: "Mary Adams",
    title: "30-day post-enrollment check-in",
    description: "Call to ensure plan is working well",
    dueDate: day(0),
    createdAt: day(-14),
  },
  {
    id: "task-2",
    relatedType: "Lead",
    relatedId: "lead-1",
    relatedName: "Robert Johnson",
    title: "Follow up on voicemail",
    dueDate: day(0),
    createdAt: day(-1),
  },
  {
    id: "task-3",
    relatedType: "Lead",
    relatedId: "lead-4",
    relatedName: "Jennifer Davis",
    title: "Return call about enrollment periods",
    dueDate: day(0),
    createdAt: day(-1),
  },
  {
    id: "task-4",
    relatedType: "Client",
    relatedId: "client-2",
    relatedName: "John Thompson",
    title: "Send Part B enrollment info",
    dueDate: day(1),
    createdAt: day(-3),
  },
  {
    id: "task-5",
    relatedType: "Lead",
    relatedId: "lead-3",
    relatedName: "Michael Brown",
    title: "Confirm Thursday appointment",
    dueDate: day(1),
    createdAt: day(-2),
  },
  {
    id: "task-6",
    relatedType: "Client",
    relatedId: "client-5",
    relatedName: "Barbara Robinson",
    title: "Research Florida plan options",
    description: "Client considering move to FL",
    dueDate: day(3),
    createdAt: day(0),
  },
  {
    id: "task-7",
    relatedType: "Client",
    relatedId: "client-3",
    relatedName: "Linda Garcia",
    title: "Annual plan review",
    dueDate: day(-1),
    createdAt: day(-7),
    completedAt: day(-2),
  },
  {
    id: "task-8",
    relatedType: "Lead",
    relatedId: "lead-6",
    relatedName: "Elizabeth Wilson",
    title: "Follow up - spouse coverage",
    dueDate: day(-2),
    createdAt: day(-3),
  },
]
