import type { Lead, Client, Activity, Task, Flow, Stage } from "./types"

// Use a fixed base date to prevent SSR/client hydration mismatches
const BASE = "2026-02-17T12:00:00.000Z"
const day = (offset: number) => {
  const d = new Date(BASE)
  d.setDate(d.getDate() + offset)
  return d.toISOString()
}

export const agents = ["Sarah Mitchell", "James Carter", "Lisa Wang"]

// Default flow and stages (same 7 as legacy LeadStage)
export const defaultFlow: Flow = {
  id: "flow-leads",
  name: "Leads",
  order: 0,
  isDefault: true,
  createdAt: BASE,
}

const STAGE_IDS = {
  New: "stage-new",
  Contacted: "stage-contacted",
  Scheduled: "stage-scheduled",
  "No-Show": "stage-no-show",
  Nurture: "stage-nurture",
  Converted: "stage-converted",
  "Closed-Lost": "stage-closed-lost",
} as const

export const defaultStages: Stage[] = [
  { id: STAGE_IDS.New, flowId: defaultFlow.id, name: "New", order: 0, colorKey: "#EF4444" },
  { id: STAGE_IDS.Contacted, flowId: defaultFlow.id, name: "Contacted", order: 1, colorKey: "#3B82F6" },
  { id: STAGE_IDS.Scheduled, flowId: defaultFlow.id, name: "Scheduled", order: 2, colorKey: "#A855F7" },
  { id: STAGE_IDS["No-Show"], flowId: defaultFlow.id, name: "No-Show", order: 3, colorKey: "#06B6D4" },
  { id: STAGE_IDS.Nurture, flowId: defaultFlow.id, name: "Nurture", order: 4, colorKey: "#EAB308" },
  { id: STAGE_IDS.Converted, flowId: defaultFlow.id, name: "Converted", order: 5, colorKey: "#22C55E" },
  { id: STAGE_IDS["Closed-Lost"], flowId: defaultFlow.id, name: "Closed-Lost", order: 6, colorKey: "#374151" },
]

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    firstName: "Robert",
    lastName: "Johnson",
    phone: "(555) 123-4567",
    email: "robert.j@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: ["Interested in Medicare Advantage plans", "Prefers morning calls"],
    tags: ["T65", "Priority"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-2),
    updatedAt: day(-1),
    nextFollowUpAt: day(1),
    dob: "1961-05-15",
  },
  {
    id: "lead-2",
    firstName: "Patricia",
    lastName: "Williams",
    phone: "(555) 234-5678",
    email: "pat.w@email.com",
    source: "Referral",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: ["Referred by existing client Mary Adams", "Has questions about Part D"],
    tags: ["Referral", "Part D"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-5),
    updatedAt: day(-1),
    nextFollowUpAt: day(2),
    dob: "1961-08-22",
  },
  {
    id: "lead-3",
    firstName: "Michael",
    lastName: "Brown",
    phone: "(555) 345-6789",
    email: "m.brown@email.com",
    source: "Website",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Scheduled,
    notes: ["Appointment set for Thursday", "Wants to compare Supplement plans"],
    tags: ["Supplement", "Appointment"],
    assignedTo: "James Carter",
    createdAt: day(-7),
    updatedAt: day(-2),
    nextFollowUpAt: day(3),
    dob: "1961-03-10",
  },
  {
    id: "lead-4",
    firstName: "Jennifer",
    lastName: "Davis",
    phone: "(555) 456-7890",
    email: "j.davis@email.com",
    source: "Call-in",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: ["Called asking about enrollment periods"],
    tags: ["T65"],
    assignedTo: "Lisa Wang",
    createdAt: day(-1),
    updatedAt: day(-1),
    nextFollowUpAt: day(0),
    dob: "1961-11-03",
  },
  {
    id: "lead-5",
    firstName: "William",
    lastName: "Miller",
    phone: "(555) 567-8901",
    email: "w.miller@email.com",
    source: "Direct Mail",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Nurture,
    notes: ["Not ready yet", "Follow up in 2 weeks", "Interested in MAPD"],
    tags: ["Long-term", "MAPD"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-30),
    updatedAt: day(-5),
    nextFollowUpAt: day(9),
  },
  {
    id: "lead-6",
    firstName: "Elizabeth",
    lastName: "Wilson",
    phone: "(555) 678-9012",
    email: "e.wilson@email.com",
    source: "Event",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: ["Met at senior center event", "Spouse also needs coverage"],
    tags: ["Couple", "Event"],
    assignedTo: "James Carter",
    createdAt: day(-3),
    updatedAt: day(-1),
    nextFollowUpAt: day(1),
    dob: "1961-07-19",
  },
  {
    id: "lead-7",
    firstName: "Thomas",
    lastName: "Anderson",
    phone: "(555) 789-0123",
    email: "t.anderson@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Converted,
    notes: ["Enrolled in Aetna MAPD plan", "Very satisfied"],
    tags: ["MAPD", "Converted"],
    assignedTo: "Lisa Wang",
    createdAt: day(-45),
    updatedAt: day(-3),
    nextFollowUpAt: null,
    dob: "1960-12-08",
  },
  {
    id: "lead-8",
    firstName: "Margaret",
    lastName: "Taylor",
    phone: "(555) 890-1234",
    email: "m.taylor@email.com",
    source: "Referral",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS["Closed-Lost"],
    notes: ["Went with another agent", "May reconsider at AEP"],
    tags: ["Lost"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-60),
    updatedAt: day(-10),
    nextFollowUpAt: null,
  },
  {
    id: "lead-9",
    firstName: "Charles",
    lastName: "Moore",
    phone: "(555) 901-2345",
    email: "c.moore@email.com",
    source: "Website",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.New,
    notes: ["Submitted form online"],
    tags: ["Online", "T65"],
    assignedTo: "James Carter",
    createdAt: day(0),
    updatedAt: day(0),
    nextFollowUpAt: day(1),
    dob: "1961-09-25",
  },
  {
    id: "lead-10",
    firstName: "Sandra",
    lastName: "Jackson",
    phone: "(555) 012-3456",
    email: "s.jackson@email.com",
    source: "Call-in",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Scheduled,
    notes: ["Appointment next Monday", "Needs help with Part B enrollment"],
    tags: ["Part B", "Appointment"],
    assignedTo: "Lisa Wang",
    createdAt: day(-4),
    updatedAt: day(-1),
    nextFollowUpAt: day(4),
  },
  {
    id: "lead-11",
    firstName: "Daniel",
    lastName: "White",
    phone: "(555) 111-2222",
    email: "d.white@email.com",
    source: "Facebook",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Contacted,
    notes: ["Interested in supplement plans"],
    tags: ["Supplement"],
    assignedTo: "Sarah Mitchell",
    createdAt: day(-6),
    updatedAt: day(-2),
    nextFollowUpAt: day(2),
  },
  {
    id: "lead-12",
    firstName: "Nancy",
    lastName: "Harris",
    phone: "(555) 333-4444",
    email: "n.harris@email.com",
    source: "Event",
    flowId: defaultFlow.id,
    stageId: STAGE_IDS.Nurture,
    notes: ["Needs to wait until retirement", "Follow up in Q4"],
    tags: ["Future"],
    assignedTo: "James Carter",
    createdAt: day(-20),
    updatedAt: day(-8),
    nextFollowUpAt: day(60),
  },
]

export const mockClients: Client[] = [
  {
    id: "client-1",
    firstName: "Mary",
    lastName: "Adams",
    phone: "(555) 100-2001",
    email: "mary.adams@email.com",
    address: "123 Oak Street",
    city: "Springfield",
    state: "IL",
    zip: "62701",
    dob: "1961-04-12",
    turning65Date: "2026-04-12",
    preferredContactMethod: "phone",
    language: "English",
    householdMembers: ["John Adams (Spouse)"],
    medicareNumber: "1EG4-TE5-MK72",
    partAEffectiveDate: "2026-04-01",
    partBEffectiveDate: "2026-04-01",
    doctors: [
      { name: "Dr. Sarah Chen", specialty: "Primary Care", phone: "(555) 200-3001" },
      { name: "Dr. James Park", specialty: "Cardiology", phone: "(555) 200-3002" },
    ],
    medications: [
      { name: "Lisinopril", dosage: "10mg", frequency: "Daily" },
      { name: "Atorvastatin", dosage: "20mg", frequency: "Daily" },
      { name: "Metformin", dosage: "500mg", frequency: "Twice daily" },
    ],
    pharmacies: [
      { name: "CVS Pharmacy", phone: "(555) 300-4001", address: "456 Main St, Springfield, IL 62701" },
    ],
    allergies: ["Penicillin"],
    conditions: ["Hypertension", "Type 2 Diabetes", "High Cholesterol"],
    coverage: {
      planType: "MAPD",
      carrier: "Aetna",
      planName: "Aetna Medicare Advantage Premier",
      effectiveDate: "2026-04-01",
      applicationId: "AET-2026-001234",
      premium: 0,
      lastReviewDate: day(-15),
    },
    createdAt: day(-90),
    updatedAt: day(-2),
  },
  {
    id: "client-2",
    firstName: "John",
    lastName: "Thompson",
    phone: "(555) 100-2002",
    email: "j.thompson@email.com",
    address: "789 Elm Avenue",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    dob: "1961-06-28",
    turning65Date: "2026-06-28",
    preferredContactMethod: "email",
    language: "English",
    medicareNumber: "2FH5-UF6-NL83",
    partAEffectiveDate: "2026-07-01",
    partBEffectiveDate: "2026-07-01",
    doctors: [
      { name: "Dr. Michael Rivera", specialty: "Primary Care", phone: "(555) 200-3003" },
    ],
    medications: [
      { name: "Omeprazole", dosage: "20mg", frequency: "Daily" },
    ],
    pharmacies: [
      { name: "Walgreens", phone: "(555) 300-4002", address: "321 State St, Chicago, IL 60601" },
    ],
    allergies: [],
    conditions: ["GERD"],
    createdAt: day(-60),
    updatedAt: day(-5),
  },
  {
    id: "client-3",
    firstName: "Linda",
    lastName: "Garcia",
    phone: "(555) 100-2003",
    email: "l.garcia@email.com",
    address: "456 Pine Road",
    city: "Naperville",
    state: "IL",
    zip: "60540",
    dob: "1961-03-05",
    turning65Date: "2026-03-05",
    preferredContactMethod: "text",
    language: "Spanish",
    medicareNumber: "3GI6-VG7-OM94",
    partAEffectiveDate: "2026-03-01",
    partBEffectiveDate: "2026-03-01",
    doctors: [
      { name: "Dr. Ana Lopez", specialty: "Primary Care", phone: "(555) 200-3004" },
      { name: "Dr. Robert Kim", specialty: "Orthopedics", phone: "(555) 200-3005" },
    ],
    medications: [
      { name: "Ibuprofen", dosage: "400mg", frequency: "As needed" },
      { name: "Calcium + D", dosage: "600mg", frequency: "Daily" },
    ],
    pharmacies: [
      { name: "Osco Pharmacy", phone: "(555) 300-4003", address: "789 Washington St, Naperville, IL 60540" },
    ],
    allergies: ["Sulfa drugs", "Latex"],
    conditions: ["Osteoarthritis"],
    coverage: {
      planType: "Supp",
      carrier: "United Healthcare",
      planName: "AARP Medigap Plan G",
      effectiveDate: "2026-03-01",
      applicationId: "UHC-2026-005678",
      premium: 148.5,
      lastReviewDate: day(-30),
    },
    createdAt: day(-120),
    updatedAt: day(-1),
  },
  {
    id: "client-4",
    firstName: "James",
    lastName: "Martinez",
    phone: "(555) 100-2004",
    email: "j.martinez@email.com",
    address: "101 Maple Drive",
    city: "Peoria",
    state: "IL",
    zip: "61602",
    dob: "1961-08-17",
    turning65Date: "2026-08-17",
    preferredContactMethod: "phone",
    language: "English",
    medicareNumber: "4HJ7-WH8-PN05",
    partAEffectiveDate: "2026-09-01",
    partBEffectiveDate: "2026-09-01",
    doctors: [
      { name: "Dr. Emily Watson", specialty: "Primary Care", phone: "(555) 200-3006" },
      { name: "Dr. David Lee", specialty: "Pulmonology", phone: "(555) 200-3007" },
    ],
    medications: [
      { name: "Albuterol", dosage: "90mcg", frequency: "As needed" },
      { name: "Fluticasone", dosage: "50mcg", frequency: "Twice daily" },
    ],
    pharmacies: [
      { name: "Rite Aid", phone: "(555) 300-4004", address: "555 Adams St, Peoria, IL 61602" },
    ],
    allergies: ["Aspirin"],
    conditions: ["Asthma", "Seasonal Allergies"],
    createdAt: day(-45),
    updatedAt: day(-3),
  },
  {
    id: "client-5",
    firstName: "Barbara",
    lastName: "Robinson",
    phone: "(555) 100-2005",
    email: "b.robinson@email.com",
    address: "222 Cedar Lane",
    city: "Evanston",
    state: "IL",
    zip: "60201",
    dob: "1961-02-20",
    turning65Date: "2026-02-20",
    preferredContactMethod: "email",
    language: "English",
    medicareNumber: "5IK8-XI9-QO16",
    partAEffectiveDate: "2026-03-01",
    partBEffectiveDate: "2026-03-01",
    doctors: [
      { name: "Dr. Mark Stevens", specialty: "Primary Care", phone: "(555) 200-3008" },
      { name: "Dr. Karen White", specialty: "Endocrinology", phone: "(555) 200-3009" },
    ],
    medications: [
      { name: "Levothyroxine", dosage: "50mcg", frequency: "Daily" },
      { name: "Vitamin B12", dosage: "1000mcg", frequency: "Daily" },
    ],
    pharmacies: [
      { name: "CVS Pharmacy", phone: "(555) 300-4005", address: "888 Central St, Evanston, IL 60201" },
    ],
    allergies: [],
    conditions: ["Hypothyroidism"],
    coverage: {
      planType: "MA",
      carrier: "Humana",
      planName: "Humana Gold Plus",
      effectiveDate: "2026-03-01",
      applicationId: "HUM-2026-009012",
      premium: 29,
      lastReviewDate: day(-7),
    },
    createdAt: day(-150),
    updatedAt: day(0),
  },
  {
    id: "client-6",
    firstName: "Richard",
    lastName: "Lee",
    phone: "(555) 100-2006",
    email: "r.lee@email.com",
    address: "333 Birch Court",
    city: "Rockford",
    state: "IL",
    zip: "61101",
    dob: "1961-10-09",
    turning65Date: "2026-10-09",
    preferredContactMethod: "phone",
    language: "English",
    medicareNumber: "6JL9-YJ0-RP27",
    partAEffectiveDate: "2026-10-01",
    partBEffectiveDate: "2026-10-01",
    doctors: [
      { name: "Dr. Susan Brown", specialty: "Primary Care", phone: "(555) 200-3010" },
    ],
    medications: [],
    pharmacies: [
      { name: "Walgreens", phone: "(555) 300-4006", address: "444 State St, Rockford, IL 61101" },
    ],
    allergies: [],
    conditions: [],
    createdAt: day(-30),
    updatedAt: day(-4),
  },
]

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    relatedType: "Client",
    relatedId: "client-1",
    type: "call",
    description: "Initial enrollment call - discussed MAPD options",
    outcome: "Scheduled follow-up",
    createdAt: day(-30),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-2",
    relatedType: "Client",
    relatedId: "client-1",
    type: "appointment",
    description: "In-person enrollment meeting",
    outcome: "Enrolled in Aetna MAPD Premier",
    createdAt: day(-15),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-3",
    relatedType: "Client",
    relatedId: "client-1",
    type: "email",
    description: "Sent welcome packet and plan summary",
    createdAt: day(-14),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-4",
    relatedType: "Lead",
    relatedId: "lead-1",
    type: "call",
    description: "Initial contact - left voicemail",
    outcome: "No answer",
    createdAt: day(-1),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-5",
    relatedType: "Lead",
    relatedId: "lead-2",
    type: "text",
    description: "Sent intro text with appointment link",
    outcome: "Replied - interested",
    createdAt: day(-2),
    createdBy: "Sarah Mitchell",
  },
  {
    id: "act-6",
    relatedType: "Client",
    relatedId: "client-3",
    type: "call",
    description: "Annual review call - reviewed current coverage",
    outcome: "Satisfied with current plan",
    createdAt: day(-1),
    createdBy: "James Carter",
  },
  {
    id: "act-7",
    relatedType: "Lead",
    relatedId: "lead-3",
    type: "email",
    description: "Sent comparison of Supplement plans",
    createdAt: day(-3),
    createdBy: "James Carter",
  },
  {
    id: "act-8",
    relatedType: "Client",
    relatedId: "client-5",
    type: "note",
    description: "Client mentioned potential move to Florida - may need plan change",
    createdAt: day(0),
    createdBy: "Lisa Wang",
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    relatedType: "Client",
    relatedId: "client-1",
    relatedName: "Mary Adams",
    title: "30-day post-enrollment check-in",
    description: "Call to ensure plan is working well",
    dueDate: day(0),
    createdAt: day(-14),
  },
  {
    id: "task-2",
    relatedType: "Lead",
    relatedId: "lead-1",
    relatedName: "Robert Johnson",
    title: "Follow up on voicemail",
    dueDate: day(0),
    createdAt: day(-1),
  },
  {
    id: "task-3",
    relatedType: "Lead",
    relatedId: "lead-4",
    relatedName: "Jennifer Davis",
    title: "Return call about enrollment periods",
    dueDate: day(0),
    createdAt: day(-1),
  },
  {
    id: "task-4",
    relatedType: "Client",
    relatedId: "client-2",
    relatedName: "John Thompson",
    title: "Send Part B enrollment info",
    dueDate: day(1),
    createdAt: day(-3),
  },
  {
    id: "task-5",
    relatedType: "Lead",
    relatedId: "lead-3",
    relatedName: "Michael Brown",
    title: "Confirm Thursday appointment",
    dueDate: day(1),
    createdAt: day(-2),
  },
  {
    id: "task-6",
    relatedType: "Client",
    relatedId: "client-5",
    relatedName: "Barbara Robinson",
    title: "Research Florida plan options",
    description: "Client considering move to FL",
    dueDate: day(3),
    createdAt: day(0),
  },
  {
    id: "task-7",
    relatedType: "Client",
    relatedId: "client-3",
    relatedName: "Linda Garcia",
    title: "Annual plan review",
    dueDate: day(-1),
    createdAt: day(-7),
  },
  {
    id: "task-8",
    relatedType: "Lead",
    relatedId: "lead-6",
    relatedName: "Elizabeth Wilson",
    title: "Follow up - spouse coverage",
    dueDate: day(-2),
    createdAt: day(-3),
  },
]
