export { ContactSection } from "./contact-section"
export { HealthSection } from "./health-section"
export { MedicareSection } from "./medicare-section"
export { CoverageSection } from "./coverage-section"
export { NotesSection } from "./notes-section"
export type { SectionProps, SectionId } from "./types"
